name = "acearchive-api"
main = "./src/index.ts"
compatibility_date = "2022-10-04"
account_id = "9d143afa60e911e9904e835bd1db8504"
usage_model = "bundled"

[env.prod]
route = "api.acearchive.lgbt"

  [[env.prod.d1_databases]]
  binding = "DB"
  database_name = "acearchive-artifacts"
  database_id = "ffd316de-0455-429b-90c7-45f935183333"

[env.dev]
route = "dev.api.acearchive.lgbt"

  [[env.dev.d1_databases]]
  binding = "DB"
  database_name = "acearchive-artifacts-dev"
  database_id = "078c47dc-e6ae-4edf-89b3-db5a6bb1b4d6"
