name = "acearchive-api"
main = "./src/index.ts"
compatibility_date = "2022-10-04"
account_id = "9d143afa60e911e9904e835bd1db8504"
usage_model = "bundled"

[route]
pattern = "api.acearchive.lgbt"
custom_domain = true

[[services]]
binding = "HASHER_WORKER"
service = "acearchive-hasher"
